import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "@/components/Providers/provider-wrapper";
import Navbar from "@/components/ui/navbar";
import { Toaster } from "sonner";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <body className={` ${geistMono.variable} antialiased`}>
        <ProviderWrapper>
          <Navbar />
          <Toaster richColors />
          {children}
        </ProviderWrapper>
      </body>
    </html>
  );
}
